// <auto-generated />
using LuciferSneaker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LuciferSneaker.Migrations
{
    [DbContext(typeof(CSDL))]
    [Migration("20191121094115_a")]
    partial class a
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LuciferSneaker.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("ChiTietDonHangID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DonHangID");

                    b.Property<decimal>("Gia");

                    b.Property<int>("GiayID");

                    b.Property<int>("SoLuong");

                    b.HasKey("ChiTietDonHangID");

                    b.HasIndex("DonHangID");

                    b.HasIndex("GiayID");

                    b.ToTable("_ChiTietDonHang");
                });

            modelBuilder.Entity("LuciferSneaker.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("ChiTietGioHangID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GiayID");

                    b.Property<string>("GioHangID");

                    b.Property<int>("SoLuong");

                    b.HasKey("ChiTietGioHangID");

                    b.HasIndex("GiayID");

                    b.HasIndex("GioHangID");

                    b.ToTable("_ChiTietGioHang");
                });

            modelBuilder.Entity("LuciferSneaker.Models.DonHang", b =>
                {
                    b.Property<int>("DonHangID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DiaChi");

                    b.Property<string>("Email");

                    b.Property<string>("HoTen");

                    b.Property<DateTime>("NgayDat");

                    b.Property<string>("SoDienThoai");

                    b.Property<decimal>("TongTien");

                    b.HasKey("DonHangID");

                    b.ToTable("_DonHang");
                });

            modelBuilder.Entity("LuciferSneaker.Models.Giay", b =>
                {
                    b.Property<int>("GiayID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Anh");

                    b.Property<decimal>("Gia");

                    b.Property<int>("LoaiGiayID");

                    b.Property<string>("MauSac");

                    b.Property<string>("MoTa");

                    b.Property<string>("Style");

                    b.Property<string>("TenGiay");

                    b.Property<bool>("TrangThai");

                    b.HasKey("GiayID");

                    b.HasIndex("LoaiGiayID");

                    b.ToTable("_Giay");
                });

            modelBuilder.Entity("LuciferSneaker.Models.GioHang", b =>
                {
                    b.Property<string>("GioHangID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("GioHangID");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("LuciferSneaker.Models.LoaiGiay", b =>
                {
                    b.Property<int>("LoaiGiayID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TenLoaiGiay");

                    b.HasKey("LoaiGiayID");

                    b.ToTable("_LoaiGiay");
                });

            modelBuilder.Entity("LuciferSneaker.Models.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MatKhau");

                    b.Property<string>("TenTaiKhoan");

                    b.HasKey("TaiKhoanID");

                    b.ToTable("_TaiKhoan");
                });

            modelBuilder.Entity("LuciferSneaker.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("LuciferSneaker.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("DonHangID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LuciferSneaker.Models.Giay", "Giay")
                        .WithMany()
                        .HasForeignKey("GiayID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LuciferSneaker.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("LuciferSneaker.Models.Giay", "Giay")
                        .WithMany()
                        .HasForeignKey("GiayID");

                    b.HasOne("LuciferSneaker.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHang")
                        .HasForeignKey("GioHangID");
                });

            modelBuilder.Entity("LuciferSneaker.Models.Giay", b =>
                {
                    b.HasOne("LuciferSneaker.Models.LoaiGiay", "LoaiGiay")
                        .WithMany()
                        .HasForeignKey("LoaiGiayID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
